### ISSUE TITLE
Restricted by copyright holders even though it shouldn't

### ISSUE THREAD

**Issue by darkangel2325** [Sorrow446/Qo-DL#117] opened 2019-09-18 10:20 UTC
I am having a problem, i can't download anything anymore, it's happening to everyone or just me?
No matter the album, it says it's restricted by copyright holders. Why is this happening?
It was working fine until today.

**Comment by girpa3** [comment] 2019-09-18 17:38
not just you. It happens to everyone. qobuz might caught up the flow of downloading through this tool.

**Comment by darkangel2325** [comment] 2019-09-18 19:01
That would be bad... so if that's the case there's nothing that can be done?

**Comment by girpa3** [comment] 2019-09-18 19:04
I am not sure. lets wait for the update. Only sorrow446 can do

**Comment by Slypser** [comment] 2019-09-19 02:58
I think the problem is the registration of the app id, as in Termux I registered before September 16 I can use it without problems, but I had to register in Qo-Dl R5D (Sorrow446 & DashLt) before September 16 to continue using it  .  Since I believe that any app id in the previous versions of the Qo-DL where the config.ini asked us for UAT will no longer work after September 16.  At least that is the only thing that occurs to me.

**Comment by Slypser** [comment] 2019-09-19 03:07
That means that everyone who didn't have the Qo-DL R5D version (Sorrow446 & DashLt) stopped working as soon as Qobuz changed app id and secret id.

**Comment by TitouanGendron** [comment] 2019-09-25 09:01
A bit late sorry, My version is still working on linux, I found the new appId and appSecret searching in the requests data with firefox. Launch a music on qobuz and search in all the requests you can found in the network tab, sorry I did this months ago, I can't help you more.
Even me with my poor skills in Internet and requests stuff I found this easily. good luck!

**Comment by MaxUgreen** [comment] 2019-09-25 23:39
> A bit late sorry, My version is still working on linux, I found the new appId and appSecret searching in the requests data with firefox. Launch a music on qobuz and search in all the requests you can found in the network tab, sorry I did this months ago, I can't help you more.
> Even me with my poor skills in Internet and requests stuff I found this easily. good luck!

Could you help me get the secret app ?. The ID app is very easy to find but I find it difficult to know the appsecret, hopefully someone continues to develop this project that in my opinion is one of the best streaming services.

**Comment by bascurtiz** [comment] 2019-09-25 23:53
Secret app = ID app md5 hashed.
1) Go to https://www.md5hashgenerator.com/ 
2) Fill in appid
3) Click generate
4) Profit

**Comment by MaxUgreen** [comment] 2019-09-26 00:17
It definitely doesn't work on PC or termux.

**Comment by bascurtiz** [comment] 2019-09-26 02:49
seems ur in a country that's not supported by Qobuz, after-all then.

**Comment by tideg** [comment] 2019-09-26 06:20
The appSecret is not the MD5-hashed appId. It is been grabbed from a resource file (bundle.js) belonging to https://play.qobuz.com. See line 87–104 in Qo-DL.py (source code). The "Restricted by copyright ..." error is not a country problem, I suppose. It seems that Qobuz has changed something so that the appId and appSecret from the web player do not work anymore for the API calls Qo-DL uses. As far as I can see the problem lies within the request signature parameter. Qobuz API-Message is: »'Invalid Request Signature parameter«. I checked the request_sig-Parameter and it seems to be correct. Compared to the web player app-id. Also app-secret and auth-token are identical.

**Comment by darkangel2325** [comment] 2019-09-27 12:23
Someday ago i tried to manually typing the id and secret id by myself after taking a look to this link https://thoas.feralhosting.com/sorrow/Qobuz-DL/App.txt, it worked, it was 5 days ago, but i lost both id and secret id cause of a pc resetting, does anyone have a photo of it?

**Comment by DavidSpek** [comment] 2019-10-01 13:28
Using the instructions provided by @bascurtiz does not cause an error regarding the appSecret. I believe, however, that the issue is maybe more complicated than just getting the right appID and appSecret combo. 

When looking at the headers and requests when playing a file, two things of interest caught my eye.
There appears to be a getFileURL followed by a file?uid=. When looking at the getFileURL request it shows the following:
`ttps://www.qobuz.com/api.json/0.2/track/getFileUrl?request_ts=1569934181&request_sig=338144dae7a4fb98e3404d6192898148&track_id=64868956&format_id=27&intent=stream`

Notice the intent=stream. If you try to go to this url you get the following response:
`{"status":"error","code":400,"message":"Invalid or missing app_id parameter"}`

If you add &app_id= with the appid you are using or from your browser session to the end of the url you get the following:
`{"track_id":64868956,"duration":30,"url":"https:\/\/sample2.qobuz.com\/file?eid=64868956&fmt=5&profile=raw&range=20-30&app_id=579169010&etsp=1569939491&hmac=k5tBYdPskkOvRmqGaNvPu_FgVVU","format_id":5,"mime_type":"audio\/mpeg","sample":true,"restrictions":[{"code":"UserUnauthenticated"}],"sampling_rate":44.1,"bit_depth":16}`

What caught my eye is the `"restrictions":[{"code":"UserUnauthenticated"}]`. 
Now I cannot know this for sure because I don't know how it was before and many of you probably know a lot more with regards to how this software works. But it seems that the software is trying to download the file using the getFileURL, which now returns that the file is restricted. I believe they may have added a more thorough check with regards to streaming access vs download access to the files. 

When going to the streaming url I am able to save a .flac file. However, this file shows as 96kHz 32 bit instead of 24 bit. So I am not sure if this is a solution. The start of the straming url, missing the app_id, cid, etsp, and hmac looks like this:
`https://streaming2.qobuz.com/file?uid=1159910&eid=64868956&fmt=7&profile=raw`

Maybe this information is of help to others trying to fix the software.

**Comment by TitouanGendron** [comment] 2019-10-01 14:38
I finally have the same problem than all of you, now I can work! :)

the problem comes from this request : 

		responset = session.get("https://www.qobuz.com/api.json/0.2/track/getFileUrl?",
				params={
					"request_ts": current_time, #unix time() command
					"request_sig": reqsighst,     #what is hard to know
					"track_id": track["id"],           
					"format_id": formatId,
					"intent": "stream"
				}
)
line 347

the request_sig is the bad guy. you get it by building a long character string following the Qobuz API : 

https://github.com/Qobuz/api-documentation
see **Signed requests authentification** 

The hard part is that we have to send the hashed secret-ID that Qobuz should have given to the developer (obiously Qobuz will never give us a secret-ID).

From now this is just speculation :

Until recently, any working secret-ID worked, but now Qobuz seems to verify if the program that ask for the track is the program corresponding to the given secret-ID.

If we whant that thing to work, we need to make it work exactly as Firefox (because Firefox is very useful to monitor the requests)

@DavidSpek In your response, you had "duration":30. Did you take a 30seconds track or was it a demo for free accounts? It could explain the "restrictions":[{"code":"UserUnauthenticated"}] ...

**Comment by DavidSpek** [comment] 2019-10-01 14:45
@TitouanGendron The duration 30 and restrictions UserUnauthenticated are not from a free demo account (free trial of the studio subscription). 

I was also onto that section of the code being the issue. Was going to play around with it to see what I can come up with. Basically, we just need it to return the file?uid=, however, I am not sure if that is what Qo-DL was doing already or if it was simply grabbing the file from the getFileURL. Thanks  for linking the api documents, hadn't looked for them yet but they should be useful.

**Comment by TitouanGendron** [comment] 2019-10-01 14:50
I think the app-secret changed. I can't get the same request_sig than firefox with any of the app_secret I have...

**Comment by MaxUgreen** [comment] 2019-10-02 18:20
Guys I found a way if it could be said, in developer tool you must find a link I leave it at the end (Obviously in appId it takes the one of your account) they open it in another tab and look at the magic. 

https://streaming2.qobuz.com/file?uid=1164517&eid=64859949&fmt=7&profile=raw&app_id=xxxxxxxxx&cid=664414&etsp=1570043503&hmac=1XLg0jeviGVuYiBDD4B9kXyVsis

**Comment by DavidSpek** [comment] 2019-10-02 18:24
@MaxUgreen

Yes this is the same link I am talking about. However, for Qo-DL to work it needs to grab that link automatically. The issue is the the signature from the link before that allows the grabbing of this link. That signature is an MD5 hash of a few calculated values one of which is the appsecret. In the Qo-DL code a static secret is used for this signature calculation which I believe is the issue.

**Comment by MaxUgreen** [comment] 2019-10-02 18:32
I am in groups in FB someone shared a video where I download, I use a chrome extension (According to my perception) called "Qobuzter" that works by obtaining the link stream and download it in the browser

**Comment by TheSunKingXIV** [comment] 2019-10-03 03:55
> https://streaming2.qobuz.com/file?uid=1164517&eid=64859949&fmt=7&profile=raw&app_id=xxxxxxxxx&cid=664414&etsp=1570043503&hmac=1XLg0jeviGVuYiBDD4B9kXyVsis

Where exactly is the link, I've tried, but I can't find it!

**Comment by Superhackman** [comment] 2019-10-03 09:12
@MaxUgreen please share chrome extension

**Comment by TheSunKingXIV** [comment] 2019-10-03 14:56
> I am in groups in FB someone shared a video where I download, I use a chrome extension (According to my perception) called "Qobuzter" that works by obtaining the link stream and download it in the browser

We need more information, please, explain the process.

**Comment by MaxUgreen** [comment] 2019-10-04 01:29
![getfvid_72572425_143532406909318_2866760012613345817_n](https://user-images.githubusercontent.com/55816392/66174641-ac41a700-e61b-11e9-882e-212588fa2978.gif)

You can see it here, try downloading with the link today but it says "Access has been denied!

**Comment by L0nelyW0lf** [comment] 2019-10-04 02:16
hey can u share that qobuzter extension? or where can i get

**Comment by MaxUgreen** [comment] 2019-10-04 02:28
> hey can u share that qobuzter extension? or where can i get

He didn't share it, I'm still looking for the extension. (Access has been denied!)
![Captura](https://user-images.githubusercontent.com/55816392/66176817-c59b2100-e624-11e9-8bbd-ec7cb329c394.PNG)

**Comment by ImAiiR** [comment] 2019-10-04 05:13
Once Qo-DL stopped working, I was still able to download the files directly by starting a stream, but seems that's been fixed now. Along with that, Qobuz removed or made private their API GitHub. All I have are screenshots of the pages I could.

**Comment by nihalsharma** [comment] 2019-10-04 05:48
I am getting the same issue due to the signature issue. Any fix yet or Qobuz has blocked these APIs for now? Nothing seems to work.

**Comment by Superhackman** [comment] 2019-10-04 08:48
qo dl, is not the only one affected, strawberry player and other repositories that the developers have done are also affected and apparently the people of qobuz got tired and bothered that they used their appid and appsecret illegally exceeding the limits of use and that is why they took the decision to remove your api documentation from github

**Comment by Superhackman** [comment] 2019-10-04 08:54
the bad thing that the developers that this repository have abandoned

**Comment by TheSunKingXIV** [comment] 2019-10-04 13:43
This seems to be the end guys... :/

**Comment by relax1980** [comment] 2019-10-04 13:45
I think so, too

**Comment by DashLt** [comment] 2019-10-05 02:48
hey cool I got some free time

**Closed** 2019-10-05 02:48 UTC
