### ISSUE TITLE
An exception has accured

### ISSUE THREAD

**Issue by fominator** [Sorrow446/Qo-DL#101] opened 2019-08-09 21:23 UTC
Sometimes i get this message and download stops. What does this mean?

Signed in successfully - Qobuz Studio account.

Input Qobuz Player or Qobuz store URL:
https://play.qobuz.com/album/0060253764852
John Coltrane - Blue Train:
Downloading track 01 of 05: Blue Train - 24 bits / 192 kHz - 2 channels
 [*] 492.1 MB / 492.1 MB @ 283 kB/s [##################] [100%, 0s left]
Downloading track 02 of 05: Moment's Notice - 24 bits / 192 kHz - 2 channels
 [*] 426.1 MB / 426.1 MB @ 955 kB/s [##################] [100%, 0s left]
Downloading track 03 of 05: Locomotion - 24 bits / 192 kHz - 2 channels
 [*] 340.1 MB / 340.1 MB @ 0 bytes/s [##################] [100%, 0s left]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "http\client.py", line 1406, in connect
  File "http\client.py", line 938, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 748, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\pySmartDL\pySmartDL.py", line 635, in post_threadpool_actions
  File "site-packages\pySmartDL\pySmartDL.py", line 330, in retry
  File "site-packages\pySmartDL\pySmartDL.py", line 257, in start
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>

Traceback (most recent call last):
  File "urllib\request.py", line 1317, in do_open
  File "http\client.py", line 1244, in request
  File "http\client.py", line 1290, in _send_request
  File "http\client.py", line 1239, in endheaders
  File "http\client.py", line 1026, in _send_output
  File "http\client.py", line 966, in send
  File "http\client.py", line 1406, in connect
  File "http\client.py", line 938, in connect
  File "socket.py", line 707, in create_connection
  File "socket.py", line 748, in getaddrinfo
socket.gaierror: [Errno 11002] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Qo-DL.py", line 780, in <module>
  File "Qo-DL.py", line 773, in init
  File "Qo-DL.py", line 485, in preRip
  File "Qo-DL.py", line 389, in rip
  File "site-packages\pySmartDL\pySmartDL.py", line 318, in start
  File "site-packages\pySmartDL\pySmartDL.py", line 477, in wait
  File "threading.py", line 926, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "site-packages\pySmartDL\pySmartDL.py", line 635, in post_threadpool_actions
  File "site-packages\pySmartDL\pySmartDL.py", line 330, in retry
  File "site-packages\pySmartDL\pySmartDL.py", line 257, in start
  File "urllib\request.py", line 222, in urlopen
  File "urllib\request.py", line 525, in open
  File "urllib\request.py", line 543, in _open
  File "urllib\request.py", line 503, in _call_chain
  File "urllib\request.py", line 1360, in https_open
  File "urllib\request.py", line 1319, in do_open
urllib.error.URLError: <urlopen error [Errno 11002] getaddrinfo failed>

An exception has occurred. Press enter to exit.v

**Comment by DashLt** [comment] 2019-08-10 15:15
This is an issue with the downloader we use. Duplicate of #90.

**Closed by DashLt** 2019-08-10 15:15 UTC
Labels: duplicate
